name: Pull Request Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
        id: go
      - uses: actions/checkout@v4
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
